### PR TITLE
Fix inotify backend for FreeBSD

### PR DESCRIPTION
**Pull request by michaelvobrien**
On FreeBSD (and possibly Linux) using `inotify-tools`:

Given:

```
{:ok, pid} = FileSystem.start_link(dirs: ["/path/to/some/files"])
```

Results in the error:

```
Couldn't watch modify: No such file or directory
````

This is similar to executing `inotifywait modify` at the console.

This fix ensures arguments to 'sh' are passed properly.

### CODE REVIEW

**Comment by michaelvobrien** [comment]
Note https://github.com/phoenixframework/phoenix_live_reload/issues/65

**Comment by falood** [comment]
Thanks @michaelvobrien , but it seems this change break linux, I'll take a look

**Comment by michaelvobrien** [comment]
@falood Yeah, I noticed that it broke Linux during the Travis tests, so the current patch has an explicit check for FreeBSD instead. The Linux code path should be the same as before.

Thank you for reviewing to make sure it's all good!

**Comment by falood** [comment]
Thanks ❤️

**Comment by michaelvobrien** [comment]
@falood Thank you! Could you please release a new version that includes this merge?

**Pull request merged**
